// @ts-check

/**
 * docs/ 폴더 구조에서 사이드바를 자동 생성합니다.
 * 폴더의 순서/이름은 각 폴더의 _category_.json 에서,
 * 문서의 순서는 각 문서 맨 위 frontmatter의 sidebar_position 으로 조정합니다.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
